
CCOPTIONS += -I./NESCore

SOURCES = srce/wgt_nesctrl.c \
	NESCore/APU.c \
	NESCore/APU_FDS.c \
	NESCore/APU_FME7.c \
	NESCore/APU_INTERNAL.c \
	NESCore/APU_MMC5.c \
	NESCore/APU_N106.c \
	NESCore/APU_VRC6.c \
	NESCore/APU_VRC7.c \
	NESCore/Config.c \
	NESCore/Cpu.c \
	NESCore/Crclib.c \
	NESCore/DirectDraw.c \
	NESCore/DirectInput.c \
	NESCore/DirectSound.c \
	NESCore/emu2413.c \
	NESCore/Mapper.c \
	NESCore/MapperFactory.c \
	NESCore/MMU.c \
	NESCore/Nes.c \
	NESCore/PAD.c \
	NESCore/PPU.c \
	NESCore/ROM.c \
	NESCore/VsUnisystem.c



#MAKEFILES=

